[main]
    separator = "|"
    description = "Stop przekrętom"
    canonifyAssetsURLs = true
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    titleCase = false
    netlifyBadge = true
    [main.colorMode]
        enabled = true
        modes = ["light", "dark"]
    [main.padding]
        x = 4
        y = 0

    [main.externalLinks]
        cue = false
        tab = true
    [main.build]
        transpiler = "libsass"

[modules]
    [modules.bootstrap]
        integration = "core"
        excludeSCSS = true
    [modules.katex]
        # integration = "core"
        disableTemplate = true
        state = "defer"
    [modules.flexsearch]
        integration = "core"
        frontmatter = false
        filter = ""
    [modules.fontawesome]
        integration = "core"
        inline = true
        debug = true
        skipMissing = false
    [modules.ModsForHinode]
        integration = "core"

[debugging]
    showJS = false
    showSCSS = true
    purgeHTMLComments = true # prevents a Goldmark warning when processing HTML comments (as used by markdownlint)

[home]
    sections = ["blog", "authors"]
    fullCover = false
    centerHeadline = true
    style = ""
    heroBanner = "/images/slider/hero-area.jpg"
    [home.feature]
        orientation = "horizontal"
        color = ""
        width = 6
        align = "start"

[navigation]
    anchor = false
    logo = "images/logo.png"
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.5rem"
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

    [navigation.search]
        enabled = false
        modal = true

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "Reddit"
    url = "https://reddit.com/submit/?url={url}&amp;resubmit=true&amp;title={title}"
    icon = "fab reddit"
    weight = 1

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "X"
    url = "https://x.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[favicon]
    logo = "images/stop-256x256.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#d43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    themeFontPreload = "/fonts/inter-v13-latin_latin-ext-regular.woff2"
    purge = false # TODO: fix purge setting of example site
# toml-docs-end theme-colors

[schema]
    type = "Organization"
    name = "Filters Heroes"
    locale = "pl"
    github = "https://github.com/FiltersHeroes"
    section = "blog"
    [author]
        name = "Filters Heroes"

[opengraph]
    images = ["images/logo.png"]
    locale = "pl"

[links]
    # bs_badge_heading = "https://getbootstrap.com/docs/5.3/components/badge/#headings"
    # hinode_docs = "https://gethinode.com"
    # hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
    # mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
    # observatory = "https://observatory.mozilla.org/analyze/demo.gethinode.com"
    # pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.gethinode.com%2F"
    # hinode = "https://gethinode.com"
# [staticmanComments]
#     notifications = "false"
#     api = "https://api.staticman.net/v3/entry/github/FiltersHeroes/KADAntiScam.netlify.app/master/comments"
[giscusComments]
    # The GitHub repository, required.
    repo = "FiltersHeroes/KADAntiScam.netlify.app"
    # The GitHub repository ID, optional. We'll fetch the repo ID by GitHub REST API if omitted.
    # It's recommend to specify it to save the build time.
    repo_id = "MDEwOlJlcG9zaXRvcnkxNjgwNTI2NDQ="

    # Discussion category, required.
    category = "Comments"
    # Discussion category ID, required, since GitHub doesn't provide REST API for discussions.
    category_id = "DIC_kwDOCgRHpM4CeIlu"

    # The mapping between the embedding page and the embedded discussion. Available options:
    #   pathname: giscus will search for a discussion whose title contains the page's pathname URL component.
    #   URL:      giscus will search for a discussion whose title contains the page's URL.
    #   title:    giscus will search for a discussion whose title contains the page's <title> HTML tag.
    #   og:title: giscus will search for a discussion whose title contains the page's <meta property="og:title"> HTML tag.
    mapping = "og:title"

    # Use strict title matching, avoid mismatches due to GitHub's fuzzy searching method when there are multiple discussions with similar titles.
    strict_matching = true

    # Theme. Available options:
    #   light:                  GitHub Light.
    #   light_high_contrast:    GitHub Light High Contrast.
    #   light_protanopia:       GitHub Light Protanopia & Deuteranopia.
    #   light_tritanopia:       GitHub Light Tritanopia.
    #   dark:                   GitHub Dark.
    #   dark_high_contrast:     GitHub Dark High Contrast.
    #   dark_protanopia:        GitHub Dark Protanopia & Deuteranopia.
    #   dark_tritanopia:        GitHub Dark Tritanopia.
    #   dark_dimmed:            GitHub Dark Dimmed.
    #   transparent_dark:       Transparent Dark.
    #   preferred_color_scheme: Preferred color scheme.
    #   an URL of external CSS. It may be unsafe, make sure you trust the author and provider of the CSS file.
    theme = "preferred_color_scheme"

    # The input position. Available options:
    #   top:    above the comments.
    #   bottom: below the comments.
    input_position = "top"

    # Enable reactions for the main post.
    reactions = true

    # Load the comments lazily.
    lazy_loading = true

    # The languages mapping from site language to Giscus language.
    # Since the Giscus doesn't support all languages and the language is case sensitive.
    # Available languages:
    #  - ar
    #  - de
    #  - gsw
    #  - es
    #  - en
    #  - fr
    #  - id
    #  - it
    #  - ja
    #  - ko
    #  - pl
    #  - pt
    #  - ro
    #  - ru
    #  - tr
    #  - vi
    #  - zh-CN
    #  - zh-TW
    [languages_mapping]
      en-us = "en"

[webmaster_verifications]
    google = "fNut01rhp845fu903ZfwVGKe-vWAz-IecDu7MHZ0bLw"