baseURL = "https://kadantiscam.netlify.app/"
languageCode = "pl-PL"
DefaultContentLanguage = "pl"
title = "KAD - stop przekrętom"
theme = "meghna-hugo"
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
ignoreFiles = [ "contactForm.html" ]

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

[permalinks]
    blog ="/blog/:year/:month/::day/:filename/"

# Menu
[[menu.main]]
name = "Działanie"
URL = "action"
weight = 2
[[menu.main]]
name = "Instrukcje"
URL = "instructions"
weight = 3
[[menu.main]]
name = "Inne polecane listy filtrów"
URL = "recommended"
weight = 4
[[menu.main]]
name = "Blog"
URL = "blog"
weight = 5
[[menu.main]]
name = "Informacje i kontakt"
URL = "contact"
weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Site params
[params]
shortTitle = "KAD - Przekręty"
includes_dir = "homepage"

home= "Start"
logo = "images/logo.png"
# Meta data
description = "Filtry blokujące strony typu przekręt i phishing"
author = "PolishFiltersTeam"
google_site_verification = "fNut01rhp845fu903ZfwVGKe-vWAz-IecDu7MHZ0bLw"

    # footer
    [params.footer]
        [[params.footer.socialIcon]]
        icon = "github"
        url = "https://github.com/PolishFiltersTeam/KADAntiScam.netlify.com"

        [[params.footer.socialIcon]]
        icon = "rss"
        url = "/index.xml"
