title: KAD - stop przekrętom
pygmentsCodeFences: true
pygmentsUseClasses: true
LanguageCode: pl-PL
DefaultContentLanguage: pl
enableEmoji: true
baseURL: https://kadantiscam.netlify.com/

params:
  use_sass: false
  show_downloads: false
  description: Filtr blokujący strony typu przekręt i phishing.
  gh_repo_owner: PolishFiltersTeam
  gh_repo_name: KAD
  author: Polish Filters Team
