[build]
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.134.2"
  GO_VERSION = "1.23.x"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --minify -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  command = "hugo --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
  # If it should show more verbose logs (optional, default = true)
  debug = true
