[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Problems"
  pageRef = "#problems"
  weight = 3

[[main]]
  name = "Hosts"
  pageRef = "#hosts"
  weight = 4

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/FiltersHeroes/KADAntiScam.netlify.app"
  weight = 20

[[social]]
  name = "RSS"
  pre = "fas fa-rss"
  url = "/index.xml"
  weight = 30
